import { db } from '@/db';
import { disaster_events } from '@/db/schema';

async function main() {
    const now = new Date();
    
    const sampleDisasterEvents = [
        {
            type: 'earthquake',
            title: 'Magnitude 6.8 Earthquake Strikes Southern Turkey',
            location: 'Gaziantep, Turkey',
            severity: 'severe',
            magnitude: 6.8,
            description: 'A powerful magnitude 6.8 earthquake struck the Turkey-Syria border region, causing significant structural damage and triggering emergency response operations across multiple provinces.',
            lat: 37.0662,
            lng: 37.3833,
            timestamp: new Date(now.getTime() - (3 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'wildfire',
            title: 'Major Wildfire Threatens Los Angeles County Communities',
            location: 'Los Angeles County, California, USA',
            severity: 'severe',
            magnitude: null,
            description: 'Fast-moving wildfire fueled by strong Santa Ana winds has forced evacuations of thousands of residents in northern Los Angeles County. Multiple structures are threatened as firefighters work to contain the blaze.',
            lat: 34.0522,
            lng: -118.2437,
            timestamp: new Date(now.getTime() - (8 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'flood',
            title: 'Severe Monsoon Flooding Impacts Dhaka Metropolitan Area',
            location: 'Dhaka, Bangladesh',
            severity: 'moderate',
            magnitude: null,
            description: 'Heavy monsoon rainfall has caused widespread flooding across Dhaka and surrounding districts. Transportation networks are severely disrupted and thousands have been displaced from low-lying areas.',
            lat: 23.8103,
            lng: 90.4125,
            timestamp: new Date(now.getTime() - (12 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'cyclone',
            title: 'Tropical Cyclone Makes Landfall in Northern Luzon',
            location: 'Luzon, Philippines',
            severity: 'severe',
            magnitude: null,
            description: 'A severe tropical cyclone with sustained winds exceeding 150 km/h has made landfall in northern Luzon, bringing torrential rain and dangerous storm surge. Evacuation centers have been activated across affected provinces.',
            lat: 14.5995,
            lng: 120.9842,
            timestamp: new Date(now.getTime() - (6 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'earthquake',
            title: 'Magnitude 5.4 Earthquake Reported Near Tokyo',
            location: 'Tokyo Metropolitan Area, Japan',
            severity: 'moderate',
            magnitude: 5.4,
            description: 'A moderate magnitude 5.4 earthquake struck offshore east of Tokyo, causing buildings to shake across the metropolitan area. No major damage has been reported and tsunami advisories have been lifted.',
            lat: 35.6762,
            lng: 139.6503,
            timestamp: new Date(now.getTime() - (15 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'storm',
            title: 'Severe Winter Storm Batters Scottish Highlands',
            location: 'Scottish Highlands, United Kingdom',
            severity: 'moderate',
            magnitude: null,
            description: 'A severe winter storm system is bringing heavy snow, strong winds, and dangerous travel conditions across Scotland. Multiple roads have been closed and power outages are affecting rural communities.',
            lat: 55.9533,
            lng: -3.1883,
            timestamp: new Date(now.getTime() - (18 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'tsunami',
            title: 'Tsunami Warning Issued for Western Sumatra Coast',
            location: 'Sumatra, Indonesia',
            severity: 'moderate',
            magnitude: null,
            description: 'Following a significant offshore earthquake, tsunami warnings have been issued for coastal areas of western Sumatra. Coastal residents are advised to move to higher ground as a precautionary measure.',
            lat: 0.5897,
            lng: 101.3431,
            timestamp: new Date(now.getTime() - (21 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'wildfire',
            title: 'Bushfire Alert for Blue Mountains Region',
            location: 'New South Wales, Australia',
            severity: 'low',
            magnitude: null,
            description: 'A bushfire burning in the Blue Mountains west of Sydney is being monitored by emergency services. The fire is currently contained but residents are advised to stay informed and prepare for potential changes in conditions.',
            lat: -33.8688,
            lng: 151.2093,
            timestamp: new Date(now.getTime() - (5 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'flood',
            title: 'Flash Flood Warning for Kerala State',
            location: 'Kerala, India',
            severity: 'low',
            magnitude: null,
            description: 'Heavy rainfall has triggered flash flood warnings in parts of Kerala. Local authorities are monitoring river levels and have issued advisories for residents in vulnerable areas to remain vigilant.',
            lat: 10.8505,
            lng: 76.2711,
            timestamp: new Date(now.getTime() - (10 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
        {
            type: 'storm',
            title: 'Tropical Storm Warning Active for Central Florida',
            location: 'Florida, USA',
            severity: 'low',
            magnitude: null,
            description: 'A tropical storm system approaching the Florida coast has prompted warnings for central and eastern counties. Residents should prepare for gusty winds, heavy rain, and possible localized flooding over the next 24 hours.',
            lat: 27.9944,
            lng: -81.7603,
            timestamp: new Date(now.getTime() - (2 * 60 * 60 * 1000)),
            userId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isActive: true,
        },
    ];

    await db.insert(disaster_events).values(sampleDisasterEvents);
    
    console.log('✅ Disaster events seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});